kumuluzee:
  name: authz-server
  version: 1.0.0-SNAPSHOT
  env:
    prod: false
    name: dev
  dev:
    scan-libraries:
      - rest-utils
  server:
    show-server-info: false
    base-url: http://localhost:8080
    http:
      port: 8080
  cors-filter:
    servlet:
      allow-origin: "*"
      supported-methods: "GET, POST, PUT, PATCH, DELETE, OPTIONS, HEAD"
      exposed-headers: "X-Total-Count,Cache-Control"
  openapi-mp:
    enabled: true
    servlet:
      mapping: /openapi/specs
    ui:
      enabled: true
      mapping: /openapi/ui
  logs:
    loggers:
      - name: ''
        level: INFO
  health:
    servlet:
      mapping: /health/
      enabled: true
    checks:
      data-source-health-check:
        type: liveness
        jndi-name: jdbc/mainDB
      disk-space-health-check:
        threshold: 100000000
        type: liveness
  datasources:
    - jndi-name: jdbc/mainDB
      connection-url: jdbc:postgresql://localhost:5432/authz-server
      username: postgres
      password: postgres
      pool:
        max-size: 20
config:
  auth:
    code:
      expiration: 5 # min
      length: 12
  token:
    access:
      expiration: 10 # min
    refresh:
      expiration: 60 # min
    id:
      expiration: 1 #min
  registration:
    enabled: true